# Generated by Django 5.1.7 on 2025-03-24 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('car_id', models.IntegerField(primary_key=True, serialize=False)),
                ('serial_number', models.CharField(max_length=50)),
                ('make', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('for_sale_yn', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.IntegerField(primary_key=True, serialize=False)),
                ('last_name', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('state_province', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('postal_code', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Mechanic',
            fields=[
                ('mechanic_id', models.IntegerField(primary_key=True, serialize=False)),
                ('last_name', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('part_id', models.IntegerField(primary_key=True, serialize=False)),
                ('part_number', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('retail_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Salesperson',
            fields=[
                ('salesperson_id', models.IntegerField(primary_key=True, serialize=False)),
                ('last_name', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('service_id', models.IntegerField(primary_key=True, serialize=False)),
                ('service_name', models.CharField(max_length=100)),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='SalesInvoice',
            fields=[
                ('invoice_id', models.IntegerField(primary_key=True, serialize=False)),
                ('invoice_number', models.IntegerField()),
                ('invoice_date', models.DateField()),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_invoices', to='core.car')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_invoices', to='core.customer')),
                ('salesperson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_invoices', to='core.salesperson')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceTicket',
            fields=[
                ('service_ticket_id', models.IntegerField(primary_key=True, serialize=False)),
                ('service_ticket_number', models.IntegerField()),
                ('date_received', models.DateField()),
                ('comments', models.TextField()),
                ('date_returned', models.DateField()),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_tickets', to='core.car')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_tickets', to='core.customer')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceMechanic',
            fields=[
                ('service_mechanic_id', models.IntegerField(primary_key=True, serialize=False)),
                ('hours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('comment', models.TextField()),
                ('rate', models.DecimalField(decimal_places=2, max_digits=8)),
                ('mechanic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_mechanics', to='core.mechanic')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_mechanics', to='core.service')),
                ('service_ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_mechanics', to='core.serviceticket')),
            ],
        ),
        migrations.CreateModel(
            name='PartsUsed',
            fields=[
                ('parts_used_id', models.IntegerField(primary_key=True, serialize=False)),
                ('number_used', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts_used', to='core.part')),
                ('service_ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts_used', to='core.serviceticket')),
            ],
        ),
    ]
